FROM ubuntu:22.04

# 필수 패키지 설치
RUN apt-get update && \
    apt-get install -y ca-certificates curl && \
    rm -rf /var/lib/apt/lists/*

# kubectl 설치 (클러스터 버전 1.28 기준)
RUN curl -fsSLo /usr/local/bin/kubectl https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl && \
    chmod +x /usr/local/bin/kubectl

# 기본 쉘을 /bin/sh 로
ENTRYPOINT ["/bin/sh"]
